import test from 'node:test';
import assert from 'node:assert/strict';
import {deflateRawSync} from 'node:zlib';
import {unpack,crc32} from '../zip.js';
import {writeFiles} from '../filesystem.js';
function zip(entries){let offset=0;const locals=[],central=[];for(const [name,body]of entries){const n=Buffer.from(name),data=Buffer.from(body),compressed=deflateRawSync(data),l=Buffer.alloc(30),c=Buffer.alloc(46);l.writeUInt32LE(0x04034b50);l.writeUInt16LE(8,8);l.writeUInt32LE(crc32(data),14);l.writeUInt32LE(compressed.length,18);l.writeUInt32LE(data.length,22);l.writeUInt16LE(n.length,26);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(8,10);c.writeUInt32LE(crc32(data),16);c.writeUInt32LE(compressed.length,20);c.writeUInt32LE(data.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(offset,42);locals.push(l,n,compressed);central.push(c,n);offset+=l.length+n.length+compressed.length;}const cd=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(cd.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,cd,end]);}
test('extract ZIP, remove wrapper folders, preserve internal resources',async()=>{const files=await unpack(zip([['repo-v1/manifest.json','{}'],['repo-v1/icons/a.txt','icon']]));assert.deepEqual(files.map(f=>f.name),['manifest.json','icons/a.txt']);assert.equal(new TextDecoder().decode(files[1].data),'icon');});
test('reject traversal, Windows aliases, collisions and corrupt content',async()=>{for(const name of ['../x','/x','C:/x','NUL','x\\y','x./a'])await assert.rejects(unpack(zip([[name,'x']])));await assert.rejects(unpack(zip([['a','x'],['A','y']])));await assert.rejects(unpack(zip([['a','x'],['a/b','y']])));const bytes=zip([['a','x']]);bytes[31]^=1;await assert.rejects(unpack(bytes));});
test('write directly into fixed project folder and commit manifest last',async()=>{const writes=[];function dir(path){return {name:'GitHub插件',getDirectoryHandle:async n=>dir(path+'/'+n),getFileHandle:async n=>({createWritable:async()=>({write:async()=>writes.push(path+'/'+n),close:async()=>{},abort:async()=>{}})})};}const files=await unpack(zip([['v1/manifest.json','{}'],['v1/content.js','script']]));const path=await writeFiles(dir('root'),'a/b',files);assert.equal(path,'GitHub插件/a_b');assert.deepEqual(writes,['root/a_b/content.js','root/a_b/manifest.json']);});
